import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";
import BottomNavbar from "@/components/layout/bottom-navbar";
import ElementRefProvider from "@/contexts/ElementRefContext";
import ThemeButton from "@/components/layout/theme-button";
import BackButton from "@/components/layout/back-button";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

// const geistMono = Geist_Mono({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <ElementRefProvider>
          <body className={`${inter.className} antialiased relative pb-20`}>
            <ThemeButton />
            <BackButton />
            {children}
            <BottomNavbar />
          </body>
        </ElementRefProvider>
      </ThemeProvider>
    </html>
  );
}
